-- ============================================================
-- Seed: 北海道 道の駅コレクション シードデータ（21件）
-- 各エリアから選出（道東6 / 道北5 / 道央7 / 道南3）
-- 全14振興局をカバー
-- ============================================================

-- 冪等性担保: 既存データがあればスキップ
TRUNCATE TABLE stations CASCADE;

INSERT INTO stations (name, name_kana, address, latitude, longitude, phone, business_hours, closed_days, website_url, image_url, area, area_group, description, facilities)
VALUES
  -- ========================================
  -- 道東 (6件)
  -- ========================================
  (
    '道の駅 阿寒丹頂の里',
    'あかんたんちょうのさと',
    '北海道釧路市阿寒町上阿寒23-36-1',
    43.0922,
    144.1019,
    '0154-66-2969',
    '9:00〜18:00（11月〜3月は10:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '釧路総合振興局',
    '道東',
    '特別天然記念物タンチョウの観察施設が隣接する道の駅。阿寒の自然と地元グルメが楽しめる。',
    '{"toilet": true, "parking": 120, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 摩周温泉',
    'ましゅうおんせん',
    '北海道川上郡弟子屈町湯の島3-5-5',
    43.4844,
    144.4581,
    '015-482-2500',
    '8:00〜18:00（11月〜4月は9:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '釧路総合振興局',
    '道東',
    '摩周湖・屈斜路湖観光の拠点となる道の駅。無料の足湯があり、ドライブの疲れを癒せる。',
    '{"toilet": true, "parking": 80, "ev_charger": true, "wifi": true, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 おんねゆ温泉',
    'おんねゆおんせん',
    '北海道北見市留辺蘂町松山1-4',
    43.7186,
    143.7092,
    '0157-45-3373',
    '8:30〜17:00（4月〜10月は8:30〜18:00）',
    '年末年始・毎週火曜（冬季）',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    'オホーツク総合振興局',
    '道東',
    '世界最大級のハト時計「果夢林」がシンボル。北の大地の水族館が併設されている。',
    '{"toilet": true, "parking": 200, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": true, "information": true}'::jsonb
  ),
  (
    '道の駅 しらぬか恋問',
    'しらぬかこいとい',
    '北海道白糠郡白糠町恋問3-3-1',
    42.9444,
    143.8417,
    '01547-2-5810',
    '9:00〜18:00（冬季は10:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '釧路総合振興局',
    '道東',
    '太平洋を一望できるロケーションが魅力。名物の豚丼や白糠産の海産物が人気。',
    '{"toilet": true, "parking": 100, "ev_charger": false, "wifi": false, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 ピア21しほろ',
    'ぴあにじゅういちしほろ',
    '北海道河東郡士幌町字士幌西2線134-1',
    43.1681,
    143.2453,
    '01564-5-3940',
    '9:00〜18:00（冬季は9:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '十勝総合振興局',
    '道東',
    '十勝平野の中心に位置する道の駅。士幌牛や地元産じゃがいもを使った料理が人気。',
    '{"toilet": true, "parking": 100, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 スワン44ねむろ',
    'すわんよんじゅうよんねむろ',
    '北海道根室市酪陽1',
    43.2842,
    145.5153,
    '0153-25-3055',
    '9:00〜17:00（5月〜10月は9:00〜18:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '根室振興局',
    '道東',
    '風蓮湖のほとりに建つ道の駅。オオハクチョウの飛来地として有名で、野鳥観察が楽しめる。',
    '{"toilet": true, "parking": 80, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),

  -- ========================================
  -- 道北 (5件)
  -- ========================================
  (
    '道の駅 びえい「白金ビルケ」',
    'びえいしろがねびるけ',
    '北海道上川郡美瑛町字白金',
    43.4425,
    142.6089,
    '0166-94-3355',
    '9:00〜18:00（11月〜4月は9:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '上川総合振興局',
    '道北',
    '白金青い池への玄関口となる道の駅。白樺林に囲まれた敷地でスイーツやクラフト体験を楽しめる。',
    '{"toilet": true, "parking": 100, "ev_charger": true, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 絵本の里けんぶち',
    'えほんのさとけんぶち',
    '北海道上川郡剣淵町東町2420',
    44.1008,
    142.3675,
    '0165-34-3811',
    '9:00〜17:00（5月〜10月は9:00〜18:00）',
    '年末年始・毎週月曜（冬季）',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '上川総合振興局',
    '道北',
    '「絵本の里」として知られる剣淵町の道の駅。絵本関連の展示やイベントが充実している。',
    '{"toilet": true, "parking": 60, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 わっかない',
    'わっかない',
    '北海道稚内市開運2丁目',
    45.4155,
    141.6731,
    '0162-29-0277',
    '10:00〜18:00（5月〜10月は9:00〜19:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '宗谷総合振興局',
    '道北',
    '日本最北端の道の駅でJR稚内駅に併設。宗谷岬や利尻・礼文島への観光拠点となっている。',
    '{"toilet": true, "parking": 50, "ev_charger": true, "wifi": true, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": true, "information": true}'::jsonb
  ),
  (
    '道の駅 もち米の里☆なよろ',
    'もちごめのさとなよろ',
    '北海道名寄市風連町西町334-1',
    44.3456,
    142.3572,
    '01655-7-8686',
    '9:00〜18:00（冬季は9:30〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '上川総合振興局',
    '道北',
    'もち米生産日本一の名寄市にある道の駅。大福やおこわなど、もち米を使った商品が名物。',
    '{"toilet": true, "parking": 80, "ev_charger": false, "wifi": true, "restaurant": false, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 おびら鰊番屋',
    'おびらにしんばんや',
    '北海道留萌郡小平町字鬼鹿広富',
    44.0567,
    141.6789,
    '0164-56-1828',
    '9:00〜17:00（5月〜10月は9:00〜18:00）',
    '年末年始・毎週月曜（冬季）',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '留萌振興局',
    '道北',
    '旧花田家番屋（国指定重要文化財）に隣接する道の駅。にしん漁の歴史と日本海の絶景が楽しめる。',
    '{"toilet": true, "parking": 70, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),

  -- ========================================
  -- 道央 (7件)
  -- ========================================
  (
    '道の駅 望羊中山',
    'ぼうようなかやま',
    '北海道虻田郡喜茂別町字川上345',
    42.8753,
    141.0264,
    '0136-33-2671',
    '8:30〜17:30（4月下旬〜10月は8:00〜18:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '後志総合振興局',
    '道央',
    '中山峠の頂上に位置し羊蹄山の眺望が見事。名物のあげいもは北海道ドライブの定番グルメ。',
    '{"toilet": true, "parking": 150, "ev_charger": false, "wifi": false, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 スペース・アップルよいち',
    'すぺーすあっぷるよいち',
    '北海道余市郡余市町黒川町6-4-1',
    43.1833,
    140.7806,
    '0135-22-1515',
    '9:00〜17:00（4月〜10月は9:00〜18:00）',
    '毎週月曜（冬季）・年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '後志総合振興局',
    '道央',
    '宇宙飛行士・毛利衛さんの出身地にちなむ宇宙をテーマにした道の駅。余市産のリンゴやワインも人気。',
    '{"toilet": true, "parking": 80, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 マオイの丘公園',
    'まおいのおかこうえん',
    '北海道夕張郡長沼町東10線南7',
    43.0086,
    141.6922,
    '0123-84-2120',
    '9:00〜18:00（11月〜3月は9:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '空知総合振興局',
    '道央',
    '石狩平野を見渡す丘の上に建つ道の駅。長沼産の新鮮な農産物の直売所が充実している。',
    '{"toilet": true, "parking": 120, "ev_charger": true, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": true, "information": true}'::jsonb
  ),
  (
    '道の駅 サーモンパーク千歳',
    'さーもんぱーくちとせ',
    '北海道千歳市花園2丁目4-2',
    42.8239,
    141.6508,
    '0123-29-3972',
    '9:00〜18:00',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '石狩振興局',
    '道央',
    '千歳川沿いに位置し、サケの遡上を間近で観察できる。新千歳空港にも近く、道央観光の拠点に便利。',
    '{"toilet": true, "parking": 200, "ev_charger": true, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": true, "information": true}'::jsonb
  ),
  (
    '道の駅 だて歴史の杜',
    'だてれきしのもり',
    '北海道伊達市松ヶ枝町34-1',
    42.4686,
    140.8564,
    '0142-25-5567',
    '9:00〜18:00（冬季は10:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '胆振総合振興局',
    '道央',
    '伊達市の歴史と文化を紹介する道の駅。藍染体験や武家屋敷の見学ができ、地元野菜の直売も充実。',
    '{"toilet": true, "parking": 150, "ev_charger": true, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": true, "information": true}'::jsonb
  ),
  (
    '道の駅 みついし',
    'みついし',
    '北海道日高郡新ひだか町三石鳧舞161-2',
    42.3033,
    142.5508,
    '0146-34-2333',
    '9:00〜17:00（5月〜10月は9:00〜18:00）',
    '年末年始・毎週月曜（冬季）',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '日高振興局',
    '道央',
    '日高昆布の産地として知られる三石にある道の駅。太平洋を望むオートキャンプ場が隣接している。',
    '{"toilet": true, "parking": 60, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),

  -- ========================================
  -- 道南 (3件)
  -- ========================================
  (
    '道の駅 縄文ロマン 南かやべ',
    'じょうもんろまんみなみかやべ',
    '北海道函館市臼尻町551-1',
    41.9631,
    140.9747,
    '0138-25-2030',
    '9:00〜17:00（4月〜10月は9:00〜18:00）',
    '毎週月曜・年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '渡島総合振興局',
    '道南',
    '国宝「中空土偶」が出土した地にある道の駅。縄文文化を紹介する展示が見どころ。',
    '{"toilet": true, "parking": 60, "ev_charger": false, "wifi": true, "restaurant": false, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 YOU・遊・もり',
    'ゆうゆうもり',
    '北海道茅部郡森町字上台町326-18',
    42.1050,
    140.5722,
    '01374-2-4886',
    '9:00〜18:00（冬季は10:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '渡島総合振興局',
    '道南',
    '噴火湾を一望できる高台にある道の駅。森町名物のいかめしや地元のスイーツが人気。',
    '{"toilet": true, "parking": 100, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  ),
  (
    '道の駅 みそぎの郷 きこない',
    'みそぎのさときこない',
    '北海道上磯郡木古内町字本町338-14',
    41.6781,
    140.4378,
    '01392-2-3161',
    '9:00〜18:00（冬季は9:00〜17:00）',
    '年末年始',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '渡島総合振興局',
    '道南',
    '北海道新幹線木古内駅に隣接する道の駅。地元食材を活かしたレストランと特産品が充実。',
    '{"toilet": true, "parking": 70, "ev_charger": true, "wifi": true, "restaurant": true, "shop": true, "baby_room": true, "handicap_toilet": true, "atm": true, "information": true}'::jsonb
  ),
  (
    '道の駅 もんじゅ',
    'もんじゅ',
    '北海道檜山郡江差町字尾山町1',
    41.8669,
    140.1228,
    '0139-52-1177',
    '9:00〜17:00（5月〜10月は9:00〜18:00）',
    '年末年始・毎週月曜（冬季）',
    'https://www.hokkaido-michinoeki.jp/',
    '/images/stations/placeholder.jpg',
    '檜山振興局',
    '道南',
    '日本海を一望できる高台に位置する道の駅。江差追分や北前船の歴史を感じられる町の玄関口。',
    '{"toilet": true, "parking": 50, "ev_charger": false, "wifi": true, "restaurant": true, "shop": true, "baby_room": false, "handicap_toilet": true, "atm": false, "information": true}'::jsonb
  );
